language: node_js
node_js:
  - 12.16

install:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH=./flutter/bin:$PATH
  - flutter doctor

script: 
  - npm link
  - npm test